name: Actualizar Google Sheet

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'  # Cada 4 horas (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Instalar dependencias
        run: pip install -r ./requirements.txt

      - name: Ejecutar script
        run: python actualizar_sheets.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
